name: chemical_scores_app
version: 1.0.0+1
publish_to: none
description: Periodic Table of Elements App
environment: 
  sdk: '>=2.16.2 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.1
  flutter: 
    sdk: flutter
  firebase_core: ^1.16.0
  firebase_auth: ^3.3.17
  firebase_storage: ^10.2.15
  cloud_firestore: ^3.1.14
  google_sign_in: ^5.3.0
  flutter_facebook_auth: ^4.3.3
  flutter_dotenv: ^5.0.2
  shared_preferences: ^2.0.15
  
dev_dependencies: 
  icons_launcher: ^1.1.7
  flutter_lints: ^1.0.0
  flutter_test: 
    sdk: flutter

flutter_icons:
  image_path: 'assets/images/chscore.png'
  ios: true
  android: true

flutter: 
  uses-material-design: true
  assets:
    - .env